# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

boxes = [
    {
        :name => "docker-host",
        :eth1 => "192.168.205.10",
        :mem => "1024",
        :cpu => "1"
    }
]

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/home/docker-host/"
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] = opts[:mem]
        v.vmx["numvcpus"] = opts[:cpu]
      end
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
      end
      config.vm.network :private_network, ip: opts[:eth1]
    end
  end
  config.vm.provision "shell", inline: <<-SHELL
    # https://docs.docker.com/engine/installation/linux/docker-ce/centos/
    # https://github.com/docker/docker-install
    sudo yum install -y git vim gcc glibc-static telnet
    git clone sudo yum install -y git vim gcc glibc-static telnet
    curl -fsSL get.docker.com -o get-docker.sh
    sh get-docker.sh
    sudo systemctl start docker
  SHELL
end
